%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_QoSAdmin
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_QOSADMIN_HRL).
-define(COSNOTIFICATION_QOSADMIN_HRL, true).




-endif.


