%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_PusherS
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_PUSHERS_HRL).
-define(OE_COSEVENTCOMM_PUSHERS_HRL, true).




-endif.


