%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_HRL).
-define(OE_COSNOTIFICATIONCOMM_HRL, true).




-endif.


