%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_HRL).
-define(COSNAMING_HRL, true).


-record('CosNaming_NameComponent', {id, kind}).
-record('CosNaming_Binding', {binding_name, binding_type}).


-endif.


