%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContext_NotEmpty
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContext_NotEmpty').
-ic_compiled("4_2_31").


-include("CosNaming_NamingContext.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",
                   "NotEmpty",[]}.

%% returns id
id() -> "IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0".

%% returns name
name() -> "CosNaming_NamingContext_NotEmpty".



