%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ConsumerAdmin
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


