%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_HRL).
-define(M_HRL, true).


-record(m_NotAnInteger, {'OE_ID'="IDL:m/NotAnInteger:1.0"}).


-endif.


