%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTime_TimeUnavailable
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTime_TimeUnavailable').
-ic_compiled("4_2_31").


-include("CosTime.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTime/TimeUnavailable:1.0",
                   "TimeUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTime/TimeUnavailable:1.0".

%% returns name
name() -> "CosTime_TimeUnavailable".



