%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventService
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTSERVICE_HRL).
-define(COSTIMEREVENT_TIMEREVENTSERVICE_HRL, true).




-endif.


