%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_TimeBase
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_TIMEBASE_HRL).
-define(OE_TIMEBASE_HRL, true).




-endif.


