%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_Directory
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_DIRECTORY_HRL).
-define(COSFILETRANSFER_DIRECTORY_HRL, true).




-endif.


