%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Coordinator
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_COORDINATOR_HRL).
-define(COSTRANSACTIONS_COORDINATOR_HRL, true).




-endif.


