%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: OrberApp
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ORBERAPP_HRL).
-define(ORBERAPP_HRL, true).




-endif.


