%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule_StackFactory
%% Source: /net/isildur/ldisk/daily_build/r15b02_prebuild_opu_o.2012-09-03_11/otp_src_R15B02/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_STACKFACTORY_HRL).
-define(STACKMODULE_STACKFACTORY_HRL, true).




-endif.


